services:
  backend:
    build: ./backend
    container_name: "${COMPOSE_PROJECT_NAME:-repodar}-backend"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT:-8000}:8000"
  backend-service:
    build: ./backend
    container_name: "${COMPOSE_PROJECT_NAME:-repodar}-backend-service"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    env_file:
      - .env
    profiles:
      - service
  frontend:
    build: 
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: "${BACKEND_URL:-http://localhost:8000}"
    container_name: "${COMPOSE_PROJECT_NAME:-repodar}-frontend"
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT:-8080}:80"
  postgres:
    image: postgres:17-alpine
    container_name: "${COMPOSE_PROJECT_NAME:-repodar}-postgres"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: "${COMPOSE_PROJECT_NAME:-repodar}-redis"
    env_file:
      - .env
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
