services:
  web:
    build: ./backend
    container_name: "${COMPOSE_PROJECT_NAME:-repodar}-web"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT:-8000}:8000"
  frontend:
    build: ./frontend
    container_name: "${COMPOSE_PROJECT_NAME:-repodar}-frontend"
    depends_on:
      - web
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT:-8080}:80"
  postgres:
    image: postgres:13-alpine
    container_name: "${COMPOSE_PROJECT_NAME:-repodar}-postgres"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: "${COMPOSE_PROJECT_NAME:-repodar}-redis"
    env_file:
      - .env
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
